### PR TITLE
Add build script

### PR DESCRIPTION
**Pull request by shaoboyan**
Usage : go to sample folder, and then run 'npm run bundle +
YOUR_SAMPLE_FOLDER_NAME'. After build, you project was been deoply in path proj/vr/build/.
NOTE: work remains
1. local node_module management : we fix some bugs in some node_module. we need hold them in local.
2. more build options, like 'npm run bundle all'.

### CODE REVIEW

**Comment by shaoboyan** [comment]
@huningxin  PTAL and Try!

**Comment by shaoboyan** [comment]
@huningxin  PTAL.

**Comment by huningxin** [comment]
It works!

But I still need to modify the 
`'../index.bundle.js',` -> `'./index.bundle.js',`
correct?

Please document all these steps in the README.md. Then we merge. Sounds good to you?

**Comment by shaoboyan** [comment]
@huningxin thx for reporting the bug ! and PTAL the latest PR.

**Comment by huningxin** [comment]
Looks good. Thanks for making this!

**Pull request merged**
